### ISSUE TITLE
Account selection for user's logged into multiple IdPs

### ISSUE THREAD

**Issue by fillup** [silinternational/simplesamlphp-module-sildisco#1]
We may need to allow users to choose which account to log in with even when they already have active login session(s) so that they can get into the app with the right identity. An example is a user having an active session using IdP1 when they logged into SP1, but then wanting to get into SP2 they could use IdP1 or IdP2 and they want to use IdP2. As it stands right now they'd automatically be logged in using the identity from IdP1 and the user would have to log out and back in again in order to get their IdP2 identity into SP2.

**Comment by Baggerone** [comment]
Added code to kill the hub's session if the user is coming from an SP that can see more than one IdP.
